version: '3'
services:
  connector-cpe:
    image: connector-crowdstrike-true-detections
    environment:
      - OPENCTI_URL=ChangeMe
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=CrowdStrikeTrueDetectionsConnector
      - CONNECTOR_SCOPE=identity,attack-pattern,course-of-action,intrusion-set,malware,tool,report
      - CONNECTOR_AUTO='False' # Enable/disable auto-import of file
      - CONNECTOR_CONFIDENCE_LEVEL=100 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - CONNECTOR_UPDATE_EXISTING_DATA='true'
      - CONNECTOR_VALIDATE_BEFORE_IMPORT='false'
      - CROWDSTRIKE_TRUE_DETECTIONS_CLIENT_ID=CHANGEME
      - CROWDSTRIKE_TRUE_DETECTIONS_CLIENT_SECRET=CHANGEME
      - CROWDSTRIKE_TRUE_DETECTIONS_INTERVAL=1
      - CROWDSTRIKE_TRUE_DETECTIONS_ORGANIZATION_NAME=ChangeMe
      - CROWDSTRIKE_TRUE_DETECTIONS_ORGANIZATIONS_MARKING_DEFINITIONS=''
      - CROWDSTRIKE_TRUE_DETECTIONS_ATTACK_PATTERNS_MARKING_DEFINITIONS=''
      - CROWDSTRIKE_TRUE_DETECTIONS_DEFAULT_MARKING_DEFINITIONS=''
    restart: always
